### ISSUE TITLE
Encryption key changes after every new app start

### ISSUE THREAD

**Issue by dasheck0** [snatik/android-storage#11]
Hi,

I just tried your library and found the interface clean and intuitive. However I also wanted to encrypt my data and thus providing an ivx and secret key. I created and loaded data and closed the app. After reopening the app crashed due to BadPaddingException when decrypting the files. I digged a little into your application and found that the secret key keeps changing whenever I restart the app. I think this is due to the salt you add to the secret key. This seems to be broken. Maybe you should have a look into that.

Best regards
dasheck

**Comment by jiyucn** [comment]
Experience the same issue. Any idea how to fix this? Thanks a lot

**Comment by dasheck0** [comment]
I didn't manage to fix it. Since I needed only the encryption part and not so much the file storage part I ended up using this https://github.com/scottyab/AESCrypt-Android Maybe you have the same setting. If so you should check this out.

**Comment by jiyucn** [comment]
Thanks a lot for your kind help.

**Comment by ZkHaider** [comment]
@dasheck0 can you explain how you used AESCrypt-Android with Simple-Storage?

**Comment by dasheck0** [comment]
Hey @ZkHaider. As I mentioned above I ended up using AESCrypt-Android in favor of Simple storage since I only needed the encryption part. I'm not sure if one can use the one with the other. But I will take a look into it once I get around the office since this is a working project.

**Comment by ZkHaider** [comment]
The issue with the key changing is inside the `SimpleStorageConfiguration` your key changes because `setEncryptContent` runs a 1000 random iterations on the key. So its different on every app startup.

**Comment by sromku** [comment]
It's a real bad bug same as here #28. 

It's a very bad thing to generate new random salt on every app session :( 
Fixed in latest version 🎉 

This looks like this:
```
// set encryption
String IVX = "abcdefghijklmnop"; // 16 lenght - not secret
String SECRET_KEY = "secret1234567890"; // 16 lenght - secret
byte[] SALT = "0000111100001111".getBytes(); // 16 byte array

// build configuration
EncryptConfiguration configuration = new EncryptConfiguration.Builder()
	.setEncryptContent(IVX, SECRET_KEY, SALT)
	.build();
	
// configure the simple storage
storage.setEncryptConfiguration(configuration);
```
