### ISSUE TITLE
Enhancement: Check if file exists in internal storage

### ISSUE THREAD

**Issue by ZkHaider** [snatik/android-storage#14]
I want to do a pull request to allow users to check if a file exists in internal memory, bet this would help out a few users!

**Comment by sromku** [comment]
@ZkHaider There is a method called: 
```
boolean isFileExist(String directoryName, String fileName);
```

I think this is what are you looking for. right?

**Comment by ZkHaider** [comment]
Not specifically, I am talking more about internal storage without specifying a directory.

**Comment by sromku** [comment]
@ZkHaider in latest version, you can set any path you want. 

``` java
boolean isFileExist(String path);
```
