### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by pixelbendr** [snatik/android-storage#17]
Hello,

How do I listen for a success or error on file creation?

**Comment by jasco** [comment]
If you look at the `createFile` interface and implementation you will get a better understanding.  It returns a boolean indicating if the file was created.  It usually throws an exception on error.

**Comment by sromku** [comment]
From latest version, there is no more runtime exceptions. You can see in logs if there was any error and you will also get boolean true/false on when the file/dir is created or not.
