### ISSUE TITLE
Save Serializable object

### ISSUE THREAD

**Issue by anticafe** [snatik/android-storage#2]
I know Serializable is not recommended in Android (should use Parcel instead), but in some situations, I want to save and read back a Serializable object.

Have you ever thought about such methods like `storage.saveSerObject(object, name)` and `storage.readSerObject(name)`?

I know with `storage.createFile("MyDirName", "fileName", "some content of the file")` and `storage.readFile` we can be easily create such methods for Serializable object, however I still would like to have them built-in.

**Comment by iballan** [comment]
@anticafe  in order to save any object, u can use Gson library, it is so powerful to convert any object to string and vice versa, just google it and u will never care about serialize objects anymore.

**Comment by sromku** [comment]
Currently the underline of storing and reading files is done with byte array. Saving `Serializable` is not planned for this lib. You can implement `Storable` interface for your objects and easy write them to disk using this lib.
