### ISSUE TITLE
Mount path /storage/emulated/0 

### ISSUE THREAD

**Issue by pcfjojo** [snatik/android-storage#21]
when i get  mount path of micro SD card on my device(LG 4C), it gives me  "/storage/9C5E-C37F/", but  this library generates the mount path like this "/storage/emulated/0" for getExternalStorage() method. 
Any solution ?

**Comment by aresares** [comment]
i have the same problem and i get `java.lang.RuntimeException: Failed to read file to input stream`

**Comment by sromku** [comment]
The library doesn't generate the path, but calls `Environment.getExternalStorageDirectory().getAbsolutePath()` internally. If you got `/storage/emulated/0` this is the path you should work with.
