### ISSUE TITLE
java.lang.RuntimeException: Failed to read file to input stream

### ISSUE THREAD

**Issue by aresares** [snatik/android-storage#22]
Hi ,i'm trying to read a file but i get this error `java.lang.RuntimeException: Failed to read file to input stream` .
The directory path that i pass is  `/storage/emulated/0/ARVirtual/texture`  and the file name is `bark_loo.jpg`

**Comment by sromku** [comment]
Hi @aresares please use latest version. I made some changes. Anyway, make sure, you accepted storage permissions in your app. 
You can also check new sample app that has many options and uses the library.
