### ISSUE TITLE
Initialization blocks main thread with a ~3600 ms init time

### ISSUE THREAD

**Issue by ZkHaider** [snatik/android-storage#24]
Having an issue I am trying to lazy load in Simple Storage but it seems to throw a fit when i initialize on another thread.

Is there a way to asynchronously load simple storage, and do I have set an encryption configuration everytime on app startup?

**Comment by sromku** [comment]
Can you please provide exactly how you are trying to load and what's the error you get. Getting files of specific path, can be done on any thread. You can also init the `Storage` in any place you want. 

For encryption. If have one instance of `Storage`, then it's enough to set encryption configuration once. For example, you create `Storage storage = new Storage(this)` in you Application class and access this object from any place in the app.
