### ISSUE TITLE
Issue In AbstractDiskStorage

### ISSUE THREAD

**Issue by ahmedshoeib** [snatik/android-storage#26]
Hi sromku , 

I face an issue in class AbstractDiskStorage specially in createDirectory

the line if (isDirectoryExists(path))  i thin you should pass name not path as you make buildPath Inside the method that cause duplication in the root path

**Comment by ahmedshoeib** [comment]
Any Updates

**Comment by ahmedshoeib** [comment]
Please Support us with this issue.

**Comment by sromku** [comment]
Hi @ahmedshoeib , I updated the lib and from latest version, all methods will use absolute paths. No more path constructions inside the lib. You should control the directories and files you wanna change. 
Please use the latest version and you can also see the full examples in our sample app ;)
