### ISSUE TITLE
isDirectoryExists() always returns true

### ISSUE THREAD

**Issue by appoll** [snatik/android-storage#27]
The result of calling the isDirectoryExists() method on an instance of the internal storage is always true. 

Easily checked by writing an androidTest:

```
@Before
public void setup() {
    Context context = InstrumentationRegistry.getTargetContext();
    storage = SimpleStorage.getInternalStorage(context);
}

@Test
public void shouldCreateTypedFolder() {
    storage.deleteDirectory("sub-" + Type.ONE);
    storage.deleteDirectory("sub-" + Type.ALL);

    // below fails
    assertFalse(storage.isDirectoryExists("sub-" + Type.ALL));
```

**Comment by sromku** [comment]
I just checked this scenario and it works for me. The latest version, has some changes. Please check the latest version and let me know if it works for you. Thanks.
