### ISSUE TITLE
Can't copy in /system folder

### ISSUE THREAD

**Issue by Silvered99** [snatik/android-storage#29]
I use the command `storage.copy(file, "/system/media/", "bootanimation.zip");` but the app crash because it wants to copy the file in /storage/emulated/0/system/media/ and not in /system/media/. How i can fix it?

**Comment by sromku** [comment]
Fixed this issue in latest version. In latest version no more relative folder and file paths, but you pass absolute path and fully control it by yourself.

Copy will look like this:

```
storage.copy(fromPath, toPath);
```
