### ISSUE TITLE
Persist data after app uninstall - getExternalStoragePublicDirectory

### ISSUE THREAD

**Issue by csbenz** [snatik/android-storage#30]
Correct me if I'm wrong, but this lib doesn't support writing to the public external storage?
So when the app is uninstalled, all data is deleted. It would be good to be able to chose between private and public external storage.

EDIT: I'm reading the docs [here](https://developer.android.com/guide/topics/data/data-storage.html#filesInternal). They don't even mention 'getExternalStorageDirectory()'. But now I understand that this latter method does **not** delete data after app uninstall. Am I correct?

**Comment by sromku** [comment]
You have internal and external storage options. The difference is just a files location on your device disk. For example, external storage will be under `/storage/emulated/0` folder. So any new folder file that will be created here, won't be deleted even if someone will uninstall your app. The internal storage will be under `/data/user/0/your.package.name` and as you can guess, once your app is deleted, the directory will be deleted as well with all folders and files inside. 

Let me know if I could clarify more, or not. Ask me anything :)
