### ISSUE TITLE
You app is empty

### ISSUE THREAD

**Issue by AnthonyKoueik** [snatik/android-storage#34]
your Sample App is empty !

**Comment by animishv** [comment]
+1, Please update your sample app code.

**Comment by chemickypes** [comment]
Hi guys, if you need you can read [TestCase class](https://github.com/sromku/android-simple-storage/blob/master/simple-storage/src/androidTest/java/com/sromku/simple/storage/StorageTestCase.java)! 

You can see a lot of example. Anyway, library is so simple that README.me can help you!

**Comment by sromku** [comment]
@chemickypes you are right, but having a sample app, will make this lib even better . Much thanks for your support 👍!

@AnthonyKoueik @animishv It's done, please check the new sample app 🎉 ;)

<img src="https://github.com/snatik/android-storage/raw/master/assets/sample_app.png"/>

**Comment by AnthonyKoueik** [comment]
thank you, i will check it out shortly
