### ISSUE TITLE
IllegalBlockSizeException

### ISSUE THREAD

**Issue by LeonXtp** [snatik/android-storage#36]
Failed to encrypt/descrypt
javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH

**Comment by sromku** [comment]
@LeonXtp please make sure that the IVX and SECRET_KEY are 16 bytes length.

```
mStorage.setEncryptConfiguration(new EncryptConfiguration.Builder()
        .setEncryptContent(IVX, SECRET_KEY, SALT)
        .build());
```
