### ISSUE TITLE
Not able to play audio file which is stored using this library 

### ISSUE THREAD

**Issue by TakeoffAndroid** [snatik/android-storage#40]
I am writing an audio file from Raw folder into Internal Storage, But unfortunately am not able to play the file from stored path using any other music player even if the files are not encrytped

**Comment by TakeoffAndroid** [comment]
`
        InputStream inStream = this.getResources().openRawResource(R.raw.demoaudio);

        byte[] music = null;
        try {
             music = new byte[inStream.available()];
        } catch (IOException e) {
            e.printStackTrace();
        }

        storageEncrypt.createFile(storageEncrypt.getExternalStorageDirectory()+ File.separator+"FolderName" + File.separator+"demoaudioencyrption.mp3"
                ,music);`

**Comment by TakeoffAndroid** [comment]
Closing this issue since its my mistake passing byte[] input. It worked like a charm later when I rectified my error.

**Comment by goonerDroid** [comment]
> 
> 
> Closing this issue since its my mistake passing byte[] input. It worked like a charm later when I rectified my error.

How did you rectify it?
