### ISSUE TITLE
java.lang.RuntimeException: Failed to encrypt/descrypt

### ISSUE THREAD

**Issue by swapps** [snatik/android-storage#9]
Hi,

i'm having this error when trying to use encryption, do you have an idea ?

02-11 10:04:41.698: E/AndroidRuntime(9964): FATAL EXCEPTION: main
02-11 10:04:41.698: E/AndroidRuntime(9964): Process: com.preiss.swapps.launcherwear, PID: 9964
02-11 10:04:41.698: E/AndroidRuntime(9964): java.lang.RuntimeException: Failed to encrypt/descrypt
02-11 10:04:41.698: E/AndroidRuntime(9964):     at com.sromku.simple.storage.security.SecurityUtil.encrypt(SecurityUtil.java:79)
02-11 10:04:41.698: E/AndroidRuntime(9964):     at com.sromku.simple.storage.AbstractDiskStorage.encrypt(AbstractDiskStorage.java:411)
02-11 10:04:41.698: E/AndroidRuntime(9964):     at com.sromku.simple.storage.AbstractDiskStorage.readFile(AbstractDiskStorage.java:386)
02-11 10:04:41.698: E/AndroidRuntime(9964):     at com.sromku.simple.storage.AbstractDiskStorage.readFile(AbstractDiskStorage.java:161)
02-11 10:04:41.698: E/AndroidRuntime(9964):     at com.sromku.simple.storage.ExternalStorage.readFile(ExternalStorage.java:1)
02-11 10:04:41.698: E/AndroidRuntime(9964):     at com.sromku.simple.storage.AbstractDiskStorage.readTextFile(AbstractDiskStorage.java:169)
02-11 10:04:41.698: E/AndroidRuntime(9964):     at com.sromku.simple.storage.ExternalStorage.readTextFile(ExternalStorage.java:1)

**Comment by sromku** [comment]
Fixed in latest version. Please check the latest version.
